# Generated by Django 3.2.9 on 2022-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
    ]
