# Generated by Django 3.2.9 on 2022-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryItem', '0002_alter_groceryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
