# Generated by Django 3.2.9 on 2022-09-16 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryItem', '0003_alter_groceryitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ('quantity', 'name')},
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='rpu',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='typ',
            field=models.CharField(choices=[['oil', 'Oil'], ['grain', 'Grain'], ['cosmetic', 'Cosmetic']], max_length=8),
        ),
    ]
